In [1]:
import json
import pandas as pd

In [8]:
df = pd.read_json('01_ppl_raw_upraveny.json')
df.head(5)

,id,accessPointType,gps,pickupEnabled,lastChange,name,capacityStatus
0,4441737,AlzaBox,"{'latitude': 49.77161, 'longitude': 18.455883}",False,2025-04-28T21:20:47.25,ABOX HVV Šrámkova (Hruška),Unknown
1,4441743,AlzaBox,"{'latitude': 49.186516, 'longitude': 16.621294}",False,2025-04-28T21:20:47.45,ABOX BRN Dornych (Lidl),Unknown
2,4441746,AlzaBox,"{'latitude': 49.872715, 'longitude': 13.894212}",False,2025-04-28T21:20:47.647,ABOX ZEB Tovární (Coop),Unknown
3,4441748,AlzaBox,"{'latitude': 49.75999, 'longitude': 16.6646}",False,2025-04-28T21:20:47.713,ABOX MTB Lanškrounská (Kubík),Unknown
4,4441749,AlzaBox,"{'latitude': 49.114958611, 'longitude': 13.825...",False,2025-04-28T21:20:47.753,ABOX ABOX CKN Čkyně,Unknown

In [9]:
df.columns

Index(['id', 'accessPointType', 'gps', 'pickupEnabled', 'lastChange', 'name',
       'capacityStatus'],
      dtype='object')

In [10]:
df[['latitude', 'longitude']] = df['gps'].apply(pd.Series)

In [11]:
df.head(5)

,id,accessPointType,gps,pickupEnabled,lastChange,name,capacityStatus,latitude,longitude
0,4441737,AlzaBox,"{'latitude': 49.77161, 'longitude': 18.455883}",False,2025-04-28T21:20:47.25,ABOX HVV Šrámkova (Hruška),Unknown,49.771610,18.455883
1,4441743,AlzaBox,"{'latitude': 49.186516, 'longitude': 16.621294}",False,2025-04-28T21:20:47.45,ABOX BRN Dornych (Lidl),Unknown,49.186516,16.621294
2,4441746,AlzaBox,"{'latitude': 49.872715, 'longitude': 13.894212}",False,2025-04-28T21:20:47.647,ABOX ZEB Tovární (Coop),Unknown,49.872715,13.894212
3,4441748,AlzaBox,"{'latitude': 49.75999, 'longitude': 16.6646}",False,2025-04-28T21:20:47.713,ABOX MTB Lanškrounská (Kubík),Unknown,49.759990,16.664600
4,4441749,AlzaBox,"{'latitude': 49.114958611, 'longitude': 13.825...",False,2025-04-28T21:20:47.753,ABOX ABOX CKN Čkyně,Unknown,49.114959,13.825538

In [12]:
df.drop(columns='gps', inplace=True)

In [13]:
df.head(5)

,id,accessPointType,pickupEnabled,lastChange,name,capacityStatus,latitude,longitude
0,4441737,AlzaBox,False,2025-04-28T21:20:47.25,ABOX HVV Šrámkova (Hruška),Unknown,49.771610,18.455883
1,4441743,AlzaBox,False,2025-04-28T21:20:47.45,ABOX BRN Dornych (Lidl),Unknown,49.186516,16.621294
2,4441746,AlzaBox,False,2025-04-28T21:20:47.647,ABOX ZEB Tovární (Coop),Unknown,49.872715,13.894212
3,4441748,AlzaBox,False,2025-04-28T21:20:47.713,ABOX MTB Lanškrounská (Kubík),Unknown,49.759990,16.664600
4,4441749,AlzaBox,False,2025-04-28T21:20:47.753,ABOX ABOX CKN Čkyně,Unknown,49.114959,13.825538

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9387 entries, 0 to 9386
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               9387 non-null   int64
 1   accessPointType  9387 non-null   object
 2   pickupEnabled    9387 non-null   bool
 3   lastChange       9387 non-null   object
 4   name             9387 non-null   object
 5   capacityStatus   9387 non-null   object
 6   latitude         9387 non-null   float64
 7   longitude        9387 non-null   float64
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 522.6+ KB

In [15]:
df['accessPointType'].value_counts()

accessPointType
ParcelBox     3708
ParcelShop    3691
AlzaBox       1988
Name: count, dtype: int64

In [17]:
alzaboxy_ppl = df[df['accessPointType'] == "AlzaBox"]
alzaboxy_ppl

,id,accessPointType,pickupEnabled,lastChange,name,capacityStatus,latitude,longitude
0,4441737,AlzaBox,False,2025-04-28T21:20:47.25,ABOX HVV Šrámkova (Hruška),Unknown,49.771610,18.455883
1,4441743,AlzaBox,False,2025-04-28T21:20:47.45,ABOX BRN Dornych (Lidl),Unknown,49.186516,16.621294
2,4441746,AlzaBox,False,2025-04-28T21:20:47.647,ABOX ZEB Tovární (Coop),Unknown,49.872715,13.894212
3,4441748,AlzaBox,False,2025-04-28T21:20:47.713,ABOX MTB Lanškrounská (Kubík),Unknown,49.759990,16.664600
4,4441749,AlzaBox,False,2025-04-28T21:20:47.753,ABOX ABOX CKN Čkyně,Unknown,49.114959,13.825538
...,...,...,...,...,...,...,...,...
9370,4727445,AlzaBox,False,2025-04-28T10:43:31.193,ABOX VAL P. Bezruče (Škola),Unknown,48.742770,16.758570
9371,4727446,AlzaBox,False,2025-04-28T10:43:31.347,ABOX TZN Litoměřická br. (Lidl),Unknown,50.513730,14.135369
9372,4727447,AlzaBox,False,2025-04-28T10:43:31.493,ABOX PSY Sportovců (Avente),Unknown,49.947876,14.526928
9373,4727448,AlzaBox,False,2025-04-28T10:43:31.71,ABOX PRG Novoborská,Unknown,50.124687,14.502355
9374,4727449,AlzaBox,False,2025-04-28T10:43:31.823,ABOX SUY Sluhy (COOP),Unknown,50.192055,14.558024

In [18]:
alzaboxy_ppl.to_csv('data_alzabox_ppl.csv', index=False, encoding='utf-8')

In [19]:
ppl_box = df[df['accessPointType'] == "ParcelBox"]
ppl_box

,id,accessPointType,pickupEnabled,lastChange,name,capacityStatus,latitude,longitude
64,4441996,ParcelBox,True,2025-05-04T15:53:50.88,PBOX HVV Dlouhá třída (OC),Free,49.775506,18.450683
65,4442021,ParcelBox,True,2025-05-04T10:13:46.9,PBOX ZNS Bratří Čapků (Bala),Free,49.563189,15.946509
66,4445468,ParcelBox,True,2025-05-04T14:33:51.737,PBOX DME Mánesova (Družba),Free,49.445367,12.927450
67,4445470,ParcelBox,True,2025-05-04T16:13:55.477,PBOX BOR Nám.republiky (Potravin),Free,49.712540,12.773685
68,4447573,ParcelBox,True,2025-05-04T12:34:00.763,PBOX BRN Kroupova (Nonstop),Free,49.165532,16.561897
...,...,...,...,...,...,...,...,...
9222,4720880,ParcelBox,True,2025-05-03T16:35:56.65,PBOX MEC Hlavní (Potravin),Free,49.908035,14.389530
9224,4720894,ParcelBox,True,2025-05-03T18:16:02.917,PBOX KMZ Spáčilova (Spáčilka),Free,49.297509,17.405806
9271,4722088,ParcelBox,True,2025-05-04T09:55:42.897,PBOX BEN Pražs.povstání (Potravin),Free,49.790014,14.698111
9276,4722298,ParcelBox,True,2025-05-03T16:55:49.16,PBOX NEW Riegrova (Zahradní),Free,49.596765,18.019427
9281,4722782,ParcelBox,True,2025-05-03T17:56:01.53,PBOX ZOE Masarykova (Lidl),Free,49.043886,16.616270

In [20]:
ppl_box.to_csv('data_ppl_box.csv', index=False, encoding='utf-8')

In [21]:
ppl_shop = df[df['accessPointType'] == "ParcelShop"]
ppl_shop

,id,accessPointType,pickupEnabled,lastChange,name,capacityStatus,latitude,longitude
2008,4550387,ParcelShop,True,2025-05-02T17:14:53.797,FIXERS - prodejna a servis elektroniky,Free,50.210250,15.832961
2009,4552313,ParcelShop,True,2025-05-02T16:14:56.927,Shopaholicmothers new,Free,49.936404,17.887953
2026,4552554,ParcelShop,True,2025-05-03T11:54:44.783,Galanterie - Fotografie Flachs,Free,49.991469,14.656686
2027,4552555,ParcelShop,True,2025-05-02T10:56:56.583,MD Újezd,Free,50.010899,14.547067
2028,4552559,ParcelShop,True,2025-05-04T16:34:48.353,Úschovna zavazadel Praha Florenc NEW,Free,50.089461,14.439714
...,...,...,...,...,...,...,...,...
9382,4727601,ParcelShop,True,2025-05-02T16:56:18.993,TVZ - Topení Voda Zásobování,Free,50.233747,12.846595
9383,4727603,ParcelShop,True,2025-05-02T09:57:50.78,Stavebniny - prodej uhlí,Free,50.891395,15.047067
9384,4727714,ParcelShop,True,2025-05-04T10:16:01.973,BAR 66,Free,49.591054,13.108395
9385,4727715,ParcelShop,True,2025-05-04T13:55:48.553,OAP - Potraviny Javorová,Free,50.624154,13.819717
9386,4727972,ParcelShop,True,2025-05-02T09:15:12.277,Drogerie Pikna new,Free,49.165982,16.564166

In [22]:
ppl_shop.to_csv('data_ppl_shop.csv', index=False, encoding='utf-8')