In [15]:
import pandas as pd

# Načtení dvou dim_box CSV souborů
path_1 = "C:/Users/Sabina/Sabi dokumenty/01 Czechitas/01 PYTHON/Python/Detektivky_vizualni_smog/sabi/data/dim_box_1.csv"
path_2 = "C:/Users/Sabina/Sabi dokumenty/01 Czechitas/01 PYTHON/Python/Detektivky_vizualni_smog/sabi/data/dim_box2.csv"

box1 = pd.read_csv(path_1, sep=";", encoding="utf-8", quotechar='"')
box2 = pd.read_csv(path_2, sep=";", encoding="utf-8", quotechar='"')

# # Sjednocení všech forem prázdných hodnot na pd.NA
# for d in [box1, box2]:
#     d.replace(["", "nan", "None"], pd.NA, inplace=True)

# Sjednocení všech forem prázdných hodnot na pd.NA
for d in [box1, box2]:
    d.replace({"": pd.NA, "nan": pd.NA, "None": pd.NA}, inplace=True)

# Sloučení obou datových rámců
df = pd.concat([box1, box2], ignore_index=True)

# Přegenerování unikátního ID
df['id'] = range(1, len(df) + 1)

# Oprava psc (odstranění .0)
df['psc'] = df['psc'].apply(lambda x: str(x).split('.')[0] if pd.notna(x) else pd.NA)

if "mesto.1" in df.columns:
    df = df.drop(columns=["mesto.1"])
    
# Oprava textových polí – nahrazení všech forem prázdnoty za ""
text_columns = ['cislo', 'psc', 'kod_obec', 'ulice', 'mesto']
for col in text_columns:
    df[col] = df[col].replace(["nan", "None", pd.NA], "").fillna("")
    df[col] = df[col].astype(str)

# # Převod typů
# df['cislo'] = df['cislo'].astype(str)
# df['psc'] = df['psc'].astype(str)
# df['kod_obec'] = df['kod_obec'].astype(str)
# df['ulice'] = df['ulice'].astype(str)
# df['mesto'] = df['mesto'].astype(str)
# df['lat'] = df['lat'].astype(float)
# df['long'] = df['long'].astype(float)

# # Převod pd.NA na prázdný řetězec a vše na string
# df = df.fillna("").astype(str)


# Export sjednoceného datasetu
df.to_csv(
    "C:/Users/Sabina/Sabi dokumenty/01 Czechitas/01 PYTHON/Python/Detektivky_vizualni_smog/sabi/data/dim_box.csv",
    sep=";",
    index=False,
    quoting=1,
    quotechar='"',
    encoding="utf-8"
)

print("Sloučený dataset s novými ID úspěšně uložen.")

Sloučený dataset s novými ID úspěšně uložen.

In [18]:
df.shape

(14031, 9)

In [19]:
chybejici_hodnoty= df[df['cislo'].str.contains(r"", na=False)]
chybejici_hodnoty

,id,id_spolecnost,kod_obec,psc,mesto,ulice,cislo,lat,long
0,1,1,586846,58601,Jihlava,S. K. Neumanna,590/22,49.4048,15.5570
1,2,1,597007,59401,Velké Meziříčí,Sokolovská,147/25,49.3517,16.0196
2,3,1,545058,75701,Valašské Meziříčí,Králova,1256,49.4693,17.9711
3,4,1,554782,15600,Praha,Pod Třešňovkou,234,49.9708,14.3832
4,5,1,511382,75002,Přerov,Svisle,1100/9,49.4503,17.4594
...,...,...,...,...,...,...,...,...,...
14026,14027,7,599832,,Sedlnice,Sedlnice,109,NaN,NaN
14027,14028,7,599867,,Spálov,Spálov,270,NaN,NaN
14028,14029,7,599930,,Suchdol nad Odrou,Komenského,140,NaN,NaN
14029,14030,7,599930,,Suchdol nad Odrou,Nová ulice,462,NaN,NaN
14030,14031,7,599930,,Suchdol nad Odrou,Za Nádražím,215,NaN,NaN