In [41]:
import pandas as pd

# Načti data
df_alza = pd.read_excel("Kopie souboru alzaboxes_enriched_ruiany.xlsx")
df_zasilkovna = pd.read_excel("Kopie souboru zasilkovna_enriched.xlsx")
df_gls = pd.read_excel("ss_clean_GLS_DATA.xlsx")

# Přidej označení zdroje
df_alza['source'] = 'alzabox'
df_zasilkovna['source'] = 'zasilkovna'
df_gls['source'] = 'gls'

# Sloučíme pod sebe
df_merged = pd.concat([df_alza, df_zasilkovna, df_gls], ignore_index=True)

# Vytvoříme nový unifikovaný ID sloupec (od 1)
df_merged['id'] = range(1, len(df_merged) + 1)

# Přesuneme 'id' na začátek (volitelné)
cols = ['id'] + [col for col in df_merged.columns if col != 'id']
df_merged = df_merged[cols]

# Ukázka výsledku
df_merged

,id,ID,name,city_code,city_code.1,zip_code,street,house_NO,latitude,longtitude,source
0,1,1,Alza Box,535826,Adamov,37371.0,Dělnická,45.0,49.000646,14.540222,alzabox
1,2,2,Alza Box,581291,Adamov,67904.0,Osvobození,440.0,49.300411,16.656003,alzabox
2,3,3,Alza Box,581291,Adamov,67904.0,Nádražní,42.0,49.300484,16.651548,alzabox
3,4,4,Alza Box,554499,Aš,35201.0,Dobrovského,2591.0,50.224082,12.198183,alzabox
4,5,5,Alza Box,554499,Aš,35201.0,Hlavní,1574.0,50.217371,12.194838,alzabox
...,...,...,...,...,...,...,...,...,...,...,...
8830,8831,969,GLS Parcel Box,585068,Zlín,76001.0,Ladislava Váchy,517,49.217261,17.633535,gls
8831,8832,970,GLS Parcel Box,582786,Brno,62700.0,Langrova,1227/1d,49.179369,16.6795328,gls
8832,8833,971,GLS Parcel Box,596230,Nové Město na Moravě,59231.0,Komenského náměstí,999,49.563083,16.0756439,gls
8833,8834,972,GLS Parcel Box,583782,Rosice,66501.0,Zastávecká,1267,49.184816,16.3680914,gls
8834,8835,973,GLS Parcel Box,582786,Brno,60200.0,Cejl,42/109,49.201348,16.6259464,gls

In [42]:
df = pd.DataFrame(df_merged)

df.head(2)

,id,ID,name,city_code,city_code.1,zip_code,street,house_NO,latitude,longtitude,source
0,1,1,Alza Box,535826,Adamov,37371.0,Dělnická,45.0,49.000646,14.540222,alzabox
1,2,2,Alza Box,581291,Adamov,67904.0,Osvobození,440.0,49.300411,16.656003,alzabox

In [43]:
df.columns

Index(['id', 'ID ', 'name', 'city_code', 'city_code.1', 'zip_code', 'street',
       'house_NO', 'latitude ', 'longtitude', 'source'],
      dtype='object')

In [44]:
df = df.drop(columns=['ID ', 'source'])

In [45]:
df = df.rename(columns={
    'id': 'ID',
    'city_code.1': 'city'
  })

In [46]:
df['zip_code'] = df['zip_code'].astype(str).str.replace(r'\.0$', '', regex=True)

In [48]:
df['house_NO'] = df['house_NO'].astype(str).str.replace(r'\.0$', '', regex=True)

In [49]:
df.head(5)

,ID,name,city_code,city,zip_code,street,house_NO,latitude,longtitude
0,1,Alza Box,535826,Adamov,37371,Dělnická,45,49.000646,14.540222
1,2,Alza Box,581291,Adamov,67904,Osvobození,440,49.300411,16.656003
2,3,Alza Box,581291,Adamov,67904,Nádražní,42,49.300484,16.651548
3,4,Alza Box,554499,Aš,35201,Dobrovského,2591,50.224082,12.198183
4,5,Alza Box,554499,Aš,35201,Hlavní,1574,50.217371,12.194838

In [ ]:
df.to_csv('gls_alza_zasilkovna_dataset_clean.csv', index=False, encoding='utf-8')